#spring.application.name=quickstart
#pizza.crust=stuffed
#pizza.sauce=bbq
#pizza.topping=chicken


#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username=postgres
#spring.datasource.password=changemeinprod!
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres


# Disable Hibernate's automatic schema creation to use schema.sql instead
spring.jpa.hibernate.ddl-auto=none
# (Optional) Ensure the initializer always runs, even if not using an embedded DB
spring.sql.init.mode=always